from __future__ import annotations

def argb_from_hex(hex: str) -> int: ...
def hex_from_argb(argb: int) -> str: ...
def theme_from_source_color() -> None: ...
def source_color_from_image() -> None: ...
def CustomColor() -> None: ...